#!/usr/bin/bash

TOUCHPAD="elan1200:00-04f3:30f7-touchpad"

if [ -z "$XDG_RUNTIME_DIR" ]; then
    XDG_RUNTIME_DIR="/run/user/$(id -u)"
    export XDG_RUNTIME_DIR
fi

export STATUS_FILE="$XDG_RUNTIME_DIR/touchpad.status"

enable_touchpad() {
    hyprctl eval "hl.device({ name = '$TOUCHPAD', enabled = true })"
    dunstify -u low "Touchpad enabled" -i "input-touchpad-on" -h string:x-dunst-stack-tag:touchpad
    printf "true" >"$STATUS_FILE"	
}

disable_touchpad() {
    hyprctl eval "hl.device({ name = '$TOUCHPAD', enabled = false })"
    dunstify -u low "Touchpad disabled" -i "input-touchpad-off" -h string:x-dunst-stack-tag:touchpad
    printf "false" >"$STATUS_FILE"
}

if ! [ -f "$STATUS_FILE" ]; then
	enable_touchpad
else
	if [ "$(cat "$STATUS_FILE")" = "true" ]; then
		disable_touchpad
	elif [ "$(cat "$STATUS_FILE")" = "false" ]; then
		enable_touchpad
	fi
fi
