#!/usr/bin/bash

wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%-

VOLUME=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -oE '[0-9]+([.][0-9]+)?' | awk '{print $1 * 100}')

# notify-send -u low "Volume $VOLUME"
dunstify -a "changeVolume" -u low -i audio-volume-high -h int:value:"$VOLUME" "Volume: ${VOLUME}%" -h string:x-dunst-stack-tag:vol

