dpi-aware=auto
icon-theme=Papirus-Dark
width=40
font=Geist:size=12
use-bold=yes
# line-height=20
fields=name,generic,comment,categories,filename,keywords
terminal=foot
prompt="❯   "
show-actions=no
exit-on-keyboard-focus-loss=no
list-executables-in-path=yes

[colors]
background=0D0E1Cff
selection=3e4284fa 
selection-text=bbbbbbff
border=00000000

[border]
radius=20
selection-radius=20

[dmenu]
exit-immediately-if-empty=yes
