# The default 16-color palette of the Linux virtual console (VGA/EGA "RGBI" defaults from
# /sys/module/vt/parameters/default_{red,grn,blu}). Dark variant.

[colors-dark]
foreground=e0e0e0
background=000000
regular0=000000 # black
regular1=a43434 # red
regular2=34a434 # green
regular3=fce94f # yellow
regular4=343ab7 # blue
regular5=a434a4 # magenta
regular6=08a2a2 # cyan
regular7=aaaaaa # light gray
bright0=555555 # bright black
bright1=ff5555 # bright red
bright2=47c566 # bright green
bright3=ffff55 # bright yellow
bright4=6497db # bright blue
bright5=a764db # bright magenta
bright6=21bcbc # bright cyan
bright7=ffffff # white
