# Inspired by The default 16-color palette of the Linux virtual console (VGA/EGA "RGBI"
# defaults from /sys/module/vt/parameters/default_{red,grn,blu}). Light variant.

[colors-light]
foreground=000000
background=ffffff
regular0=000000 # black
regular1=aa0000 # red
regular2=00aa00 # green
regular3=aa3300 # yellow
regular4=0000aa # blue
regular5=aa00aa # magenta
regular6=008888 # cyan
regular7=aaaaaa # light gray
bright0=333333 # bright black
bright1=dd3333 # bright red
bright2=33dd33 # bright green
bright3=dddd33 # bright yellow
bright4=3333dd # bright blue
bright5=dd33dd # bright magenta
bright6=00dcdc # bright cyan
bright7=ffffff # white
